// Each row: prompt, correct answer, three distractors, explanation.
module.exports = {
 'Data structures': [
 ['Which structure naturally models undoing the most recent editor action?', 'Stack', 'Queue', 'Min-heap', 'Hash set', 'A stack is last in, first out (LIFO), so the most recent action is removed first. A queue removes the oldest item first.'],
 ['Which structure efficiently implements a first-come, first-served work list?', 'Queue', 'Stack', 'Binary search tree', 'Bloom filter', 'A queue is first in, first out (FIFO). A linked queue or circular buffer supports efficient insertion at the back and removal from the front.'],
 ['What is the expected lookup cost in a well-sized hash table with a good hash function?', 'O(1)', 'O(log n)', 'O(n log n)', 'Always O(n)', 'With controlled load factor and a suitable hash function, expected lookup is constant time. Many collisions can degrade worst-case lookup to linear time in a simple implementation.'],
 ['Which operation benefits most from a linked list when a pointer to the relevant node is already available?', 'Inserting immediately after that node', 'Accessing the millionth element by index', 'Binary searching unsorted values', 'Storing values contiguously in memory', 'Inserting after a known node only updates a few links, taking O(1). Finding a node by position can still require O(n) traversal.'],
 ['In a binary min-heap, what is guaranteed?', 'Every parent is no greater than its children', 'Every left child is less than every right child', 'All elements are globally sorted', 'The tree can have arbitrary height for a fixed size', 'The heap property puts a minimum at the root. It does not sort siblings or unrelated subtrees. A binary heap also has a complete-tree shape.'],
 ['Which representation typically uses O(V + E) space for a sparse graph?', 'Adjacency list', 'Adjacency matrix', 'All-pairs distance matrix', 'A V by V Boolean table', 'Adjacency lists store vertices and their edges, using O(V + E) space. A matrix uses O(V squared), even if few edges exist.'],
 ['Which structure is especially suitable for prefix-based word lookup?', 'Trie', 'Stack', 'Disjoint-set forest', 'Unordered linked list', 'A trie shares prefixes along paths, making prefix lookup depend primarily on prefix length rather than scanning every stored word.'],
 ['What does a standard Bloom filter guarantee for membership queries, assuming correct implementation and no deletions?', 'A negative answer means the item is absent', 'A positive answer means the item is present', 'It returns the exact count of an item', 'It stores every original item verbatim', 'Bloom filters can give false positives, but not false negatives under these assumptions. A positive result needs verification when exact membership matters.']
 ],
 'Algorithms': [
 ['Which traversal finds shortest paths from one source in an unweighted graph?', 'Breadth-first search', 'Depth-first search', 'Heap sort', 'Binary search', 'BFS explores vertices by increasing edge count from the source. DFS may find a path without finding the shortest one.'],
 ['What does standard Dijkstra shortest-path search require of edge weights?', 'All edge weights must be nonnegative', 'All weights must equal one', 'The graph must be acyclic', 'Every vertex must connect to every other vertex', 'Dijkstra finalizes distances using a greedy argument that depends on nonnegative weights. Negative edges can invalidate that argument.'],
 ['Which property most directly enables binary search in an array?', 'The array is sorted under the search comparison', 'The array has an even number of elements', 'All elements are distinct', 'The array fits into a CPU cache', 'Ordering tells binary search which half cannot contain the target. Duplicates are allowed, though finding the first or last match needs a boundary-aware variant.'],
 ['Dynamic programming is especially useful when a problem has which properties?', 'Overlapping subproblems and optimal substructure', 'Only one possible solution', 'No reusable partial results', 'Only constant-size input', 'Dynamic programming reuses subproblem results. Optimal substructure lets those results compose into an optimal solution; overlapping subproblems make caching valuable.'],
 ['What does a topological ordering of a directed acyclic graph ensure?', 'Each directed edge goes from an earlier vertex to a later vertex', 'Vertices appear in numerical order', 'Every pair of consecutive vertices shares an edge', 'Every path has minimum total weight', 'A topological order respects dependency direction. A directed cycle prevents such an ordering from existing.'],
 ['What makes a sorting algorithm stable?', 'Equal-key elements preserve their original relative order', 'Its running time is constant', 'It never allocates memory', 'It works only on unique values', 'Stability matters when sorting records by multiple keys: records tied on the latest key retain their earlier order. It is unrelated to constant running time.'],
 ['For two-sum on a sorted array, why can opposite-end pointers avoid checking every pair?', 'The sum determines which pointer can move past impossible pairs', 'All pairs have the same sum', 'Sorted arrays contain no duplicate values', 'Pointer movement makes addition constant space and constant total time', 'If the sum is too small, advancing the left pointer can increase it; if too large, moving the right pointer can decrease it. Each pointer moves at most n times.'],
 ['Why does greedy coin change fail for denominations 1, 3, and 4 when making 6?', 'It chooses 4 + 1 + 1 although 3 + 3 uses fewer coins', 'The amount cannot be represented', 'Greedy algorithms always require sorting in descending time order', 'Using coin 1 is never allowed', 'A locally largest coin need not produce the global minimum count. A greedy method requires a correctness argument for the particular problem.']
 ],
 'Big-O': [
 ['A loop doubles i from 1 while i < n. What is its iteration count asymptotically?', 'Theta(log n)', 'Theta(n)', 'Theta(n squared)', 'Theta(1)', 'After k iterations, i is 2 to the k. Reaching n therefore takes about log base 2 of n steps.'],
 ['Two nested loops each run n times independently. What is the total time for constant work in the inner loop?', 'Theta(n squared)', 'Theta(n)', 'Theta(log n)', 'Theta(n log n)', 'Each of n outer iterations performs n inner iterations, giving n times n constant-time operations.'],
 ['What is the tight asymptotic growth of 3n squared + 10n + 7?', 'Theta(n squared)', 'Theta(n cubed)', 'Theta(n)', 'Theta(log n)', 'The highest-order term dominates as n grows. Constant factors and lower-order terms do not change the tight asymptotic class.'],
 ['A dynamic array doubles its capacity when full. What is the amortized cost of appending one element?', 'O(1)', 'O(log n)', 'O(n) for every append', 'O(n squared)', 'Occasional resizing costs O(n), but the total copying cost across n appends is O(n). Dividing by n gives constant amortized cost.'],
 ['A recursive function makes one recursive call on n - 1 and keeps a constant-size frame. Without tail-call optimization, what is its stack space?', 'O(n)', 'O(1)', 'O(log n)', 'O(n squared)', 'There can be n live stack frames. Constant work or storage per frame does not imply constant total stack space.'],
 ['What is the solution to T(n) = 2T(n/2) + Theta(n), with constant base cases?', 'Theta(n log n)', 'Theta(n)', 'Theta(log n)', 'Theta(n squared)', 'There are logarithmically many recursion levels, and each level does linear total work. This is the usual merge-sort recurrence.'],
 ['A loop runs over n users, and an independent later loop runs over m files. What is the total time?', 'Theta(n + m)', 'Theta(n times m)', 'Theta(log(n + m))', 'Theta(1)', 'Sequential loops add their costs. Multiplication would apply to nested loops that process every user-file pair.'],
 ['What does an O(n squared) upper bound alone tell you?', 'Growth is bounded above by a constant multiple of n squared for sufficiently large n', 'The running time is exactly n squared operations', 'The lower bound must also be n squared', 'The algorithm must be slower than every O(n) algorithm on every input', 'Big-O is an asymptotic upper bound, not an exact count or necessarily a tight bound. Constants and input sizes matter for actual performance.']
 ],
 'OOP': [
 ['What is the main purpose of encapsulation?', 'Protecting an object’s invariants through a controlled interface', 'Making all fields public', 'Requiring inheritance for every class', 'Eliminating all mutable data', 'Encapsulation groups behavior and state behind an interface so callers cannot casually violate internal assumptions. It does not require complete immutability.'],
 ['What is runtime polymorphism?', 'Calling an overridden implementation based on the actual object type', 'Choosing every method only by its name at compile time', 'Copying every base-class field into a global variable', 'Using a loop with several branches', 'Dynamic dispatch selects an implementation from the runtime object type, allowing different objects to satisfy the same interface.'],
 ['Which design best illustrates composition?', 'A Car holds an Engine object and delegates work to it', 'Car inherits from every type it uses', 'Engine exposes only static variables', 'Every class duplicates engine logic', 'Composition builds behavior from contained collaborators. It models a has-a relationship and can reduce coupling to inheritance hierarchies.'],
 ['What does the Liskov substitution principle require?', 'A subtype can replace its base type without breaking the base type’s behavioral contract', 'Every subtype has exactly the same fields', 'Base classes cannot define methods', 'All subtype methods must be faster', 'Clients relying on the base contract should still work with the subtype. Strengthening preconditions or weakening promised postconditions can violate substitution.'],
 ['Which statement distinguishes an interface from an implementation?', 'An interface describes a contract; an implementation supplies its behavior', 'An interface must always contain mutable state', 'An implementation cannot be tested', 'An interface is always a user interface', 'Interfaces describe what clients may rely on. Implementations determine how that contract is fulfilled; exact language features vary.'],
 ['What is method overloading in languages that support it?', 'Defining methods with the same name but different parameter signatures', 'Replacing inherited behavior in a subtype', 'Executing a method twice concurrently', 'Loading a class from two disks', 'Overloading is distinguished by parameter signatures. Overriding supplies a subtype implementation of an inherited method.'],
 ['Why can exposing a mutable internal list break encapsulation?', 'Callers can change internal state without enforcing the object’s rules', 'Lists cannot be stored in objects', 'Returning a list always copies it', 'The class automatically becomes abstract', 'A shared mutable reference lets callers bypass validation. A defensive copy or appropriate immutable view can help preserve invariants.'],
 ['What is an abstract class typically used for?', 'Providing a partial implementation and a common base contract', 'Guaranteeing that every method is static', 'Preventing all subclasses', 'Storing only primitive numbers', 'An abstract class can share behavior while leaving some operations to subclasses. It typically cannot be instantiated directly.']
 ],
 'Databases / SQL': [
 ['What does a LEFT JOIN preserve?', 'Every row from the left table, with NULLs for unmatched right-side columns', 'Only rows matching in both tables', 'Every row from the right table only', 'Only rows containing no NULL values', 'LEFT JOIN retains unmatched left rows. A later WHERE condition on right-side columns can still remove those rows.'],
 ['Which clause filters groups after aggregation?', 'HAVING', 'WHERE', 'ORDER BY', 'FROM', 'WHERE filters input rows before grouping; HAVING filters the groups produced by GROUP BY and aggregate expressions.'],
 ['What does atomicity mean for a database transaction?', 'All its changes commit together, or none do', 'Every query takes one CPU instruction', 'Every transaction reads the newest value at every instant', 'Only one connection can access the database', 'Atomicity prevents partial commits. Isolation concerns interactions between transactions, and durability concerns surviving failures after commit.'],
 ['Which is a typical tradeoff of adding an index?', 'Faster matching reads at the cost of storage and extra write work', 'Every write becomes faster with no cost', 'The table becomes automatically normalized', 'All queries use constant time', 'Indexes can reduce read work but must be maintained on inserts, deletes, and relevant updates. Benefit depends on query shape and selectivity.'],
 ['How should a SQL query test whether a column contains NULL?', 'column_name IS NULL', 'column_name = NULL', 'column_name == NULL', 'column_name IN NULL', 'NULL represents missing or unknown data. Equality with NULL evaluates to unknown, so SQL provides IS NULL for this test.'],
 ['What does a foreign key primarily enforce?', 'References point to permitted keys in a related table, subject to NULL and configured rules', 'Every text column contains unique values', 'Every query uses an index', 'Related tables must have the same row count', 'A foreign key enforces referential integrity. Optional NULL references and update/delete actions depend on the declared constraint.'],
 ['Why normalize relational tables?', 'To reduce redundancy and update anomalies', 'To guarantee no joins are ever needed', 'To ensure every query is faster', 'To store all data in a single row', 'Normalization organizes facts by dependencies, reducing inconsistent duplicate facts. It may introduce joins and does not guarantee faster queries.'],
 ['Two concurrent transactions read balance 100 and each writes 90 after a withdrawal of 10. What problem occurred?', 'Lost update', 'Dirty read necessarily occurred', 'The balance was correctly serialized', 'A foreign key cascade', 'One write overwrites the other’s effect. An atomic decrement, suitable locking, or a checked version can prevent this lost-update pattern.']
 ],
 'Operating systems': [
 ['What do threads in the same process typically share?', 'The process address space', 'One identical stack for all threads', 'Exactly one program counter', 'No memory at all', 'Threads generally share heap and global memory but have their own stacks, registers, and execution state. Sharing requires synchronization where needed.'],
 ['What is virtual memory primarily used to provide?', 'A per-process address abstraction mapped to physical memory', 'Unlimited physical RAM with no performance cost', 'A guarantee that every memory access hits cache', 'One shared address space for all processes', 'Virtual memory supports isolation and flexible mapping. Missing resident pages can cause faults, and memory remains physically limited.'],
 ['What happens during a context switch?', 'The OS saves one execution context and restores another', 'The CPU permanently deletes the old process', 'Every cached file is written to disk', 'The compiler recompiles the application', 'Context switching changes the running task by saving and restoring state such as registers. It adds overhead and can affect cache locality.'],
 ['What is a system call?', 'A controlled request from a program for a kernel service', 'Any call from one user function to another', 'A database query on a remote server', 'An instruction that only compilers execute', 'System calls expose kernel services such as file I/O and process management through a controlled privilege boundary.'],
 ['What is a page fault?', 'An access that requires OS handling because the current page mapping cannot satisfy it', 'Always a fatal application crash', 'Always proof that the disk is damaged', 'A CPU arithmetic overflow', 'Page faults may load a valid page, establish a mapping, or report an invalid access. They do not always require disk I/O or terminate a process.'],
 ['Which scheduling policy gives each ready task a time slice in cyclic order?', 'Round-robin', 'Shortest job first without preemption', 'Last in, first out', 'Random replacement of memory pages', 'Round-robin rotates among ready tasks. Time-slice size affects responsiveness and context-switch overhead.'],
 ['What is the difference between a program and a process?', 'A program is code; a process is a running instance with execution resources', 'They always refer to identical OS objects', 'A process is only a file stored on disk', 'A program must have exactly one process forever', 'Multiple processes can run the same program while maintaining separate execution state and usually separate address spaces.'],
 ['What is thrashing in a virtual-memory system?', 'Spending excessive time paging instead of doing useful work', 'Running only one thread', 'Using an SSD instead of a hard disk', 'Completing all tasks before their deadlines', 'When active working sets exceed available memory, frequent page replacement can dominate execution and severely reduce throughput.']
 ],
 'Networking': [
 ['What does TCP provide to an application?', 'An ordered, reliable byte stream while the connection is functioning', 'Guaranteed application message boundaries', 'Guaranteed fixed latency', 'Automatic encryption of every byte', 'TCP handles sequencing and retransmission but exposes a stream, so applications define message framing. It does not itself encrypt traffic or guarantee successful delivery despite all failures.'],
 ['What is characteristic of UDP?', 'Datagrams without built-in delivery or ordering guarantees', 'A mandatory three-way handshake before every datagram', 'Automatic retransmission of lost packets', 'A reliable ordered byte stream', 'UDP preserves datagram boundaries with minimal transport machinery. Applications can add reliability when needed.'],
 ['What is DNS commonly used for?', 'Resolving domain names to records such as IP addresses', 'Encrypting web request bodies', 'Assigning CPU time to processes', 'Compressing database tables', 'DNS is a distributed naming system. Address records help locate hosts, while other record types support mail routing and other uses.'],
 ['What is the main purpose of a subnet mask or network prefix?', 'Separating the network portion of an IP address from the host portion', 'Encrypting IP addresses', 'Determining the browser’s cookie policy', 'Guaranteeing that an IP address is public', 'The prefix identifies an IP network, helping hosts and routers decide whether a destination is local or requires forwarding.'],
 ['Which device primarily forwards packets between IP networks?', 'Router', 'Layer-2 switch acting only as a bridge', 'Keyboard controller', 'DNS cache entry', 'Routers make forwarding decisions using network-layer information and routes. A basic Layer-2 switch forwards frames within a LAN.'],
 ['How do latency and bandwidth differ?', 'Latency is delay; bandwidth is data-transfer capacity per unit time', 'They are always the same measurement', 'Latency measures disk size; bandwidth measures CPU cores', 'More bandwidth guarantees zero latency', 'A wide link can carry much data but still have long propagation delay. Improving bandwidth may not fix latency-sensitive request chains.'],
 ['What does the TCP three-way handshake establish?', 'A connection with synchronized initial sequence information', 'An encrypted TLS session by itself', 'A DNS record for the server', 'The HTTP response body before a request exists', 'SYN, SYN-ACK, and ACK establish TCP state and sequence numbers. TLS, when used, performs its own cryptographic handshake.'],
 ['What is network address translation (NAT) commonly used for?', 'Mapping internal addresses, and often ports, to external ones', 'Making all traffic cryptographically secure', 'Replacing all routing decisions', 'Increasing the physical speed of a cable', 'NAT rewrites addressing information, commonly allowing several private hosts to share a public IPv4 address. It is not encryption.']
 ],
 'Backend / web': [
 ['What does HTTP being stateless mean?', 'The protocol does not inherently require retained application-session state between requests', 'Web applications cannot implement logins', 'Servers cannot store data', 'Every request must use a different TCP connection', 'Applications add state with mechanisms such as sessions, cookies, and tokens. Stateless HTTP does not forbid server-side storage or connection reuse.'],
 ['Which HTTP method is defined as idempotent?', 'PUT', 'POST in all circumstances', 'CONNECT in all circumstances', 'No HTTP method is idempotent', 'Repeating an identical PUT is intended to have the same effect as one request. Idempotence concerns intended state effects, not necessarily identical responses.'],
 ['What does HTTP 404 generally indicate?', 'The target resource was not found or is not being disclosed', 'The request succeeded and created a resource', 'The server asks the client to retry after authentication in every case', 'The client must switch to WebSocket', '404 indicates that a current representation was not found or that the server will not disclose one. It differs from a general server error such as 500.'],
 ['What is CORS primarily about?', 'Browser enforcement of whether scripts may access responses across origins', 'Authenticating all API clients', 'Preventing requests from every non-browser client', 'Encrypting cookies in storage', 'CORS lets servers declare cross-origin access permissions to browsers. It is not a replacement for authentication or authorization.'],
 ['Why use pagination for a large API result?', 'To bound response size and processing per request', 'To ensure all results are returned atomically across every page', 'To eliminate the need for database queries', 'To make authorization unnecessary', 'Pagination limits work and payload size. Concurrent changes can affect page consistency; cursor and snapshot strategies address different parts of that problem.'],
 ['What is the N+1 query problem?', 'Fetching a list, then issuing one additional query per list item', 'Using a database with n + 1 columns', 'Returning one more row than requested', 'Running two queries concurrently', 'Repeated per-item lookups can create many database round trips. Joins, batching, or suitable eager loading can reduce the query count.'],
 ['What is an appropriate purpose for a background job queue?', 'Running slow or retryable work outside the immediate request-response path', 'Guaranteeing a job can never run twice', 'Replacing all durable data storage', 'Ensuring every task finishes instantly', 'Queues decouple request latency from work such as sending receipts. Retries and redelivery make idempotent job handling valuable.'],
 ['Why should a payment API accept an idempotency key for retries?', 'To recognize repeated attempts at the same operation and avoid duplicate effects', 'To encrypt card details without TLS', 'To give every caller administrator access', 'To force every retry to create another payment', 'The server associates the key with an operation and its result, with suitable concurrency control and retention. The key alone is not authentication.']
 ],
 'Software design': [
 ['What does the single responsibility principle emphasize?', 'A module should have one cohesive reason to change', 'Every class must contain exactly one method', 'Every application should use one file', 'Every developer may edit only one class', 'Responsibility refers to a cohesive concern and its sources of change, not a literal method count. Separating unrelated concerns reduces coupled changes.'],
 ['What does dependency inversion favor?', 'High-level policy and low-level details depending on abstractions', 'High-level policy importing every concrete storage driver directly', 'Avoiding all interfaces', 'Making all dependencies global variables', 'Abstractions decouple policy from details. Dependency injection is one technique for supplying implementations, but it is not the principle itself.'],
 ['When is the strategy pattern useful?', 'When interchangeable algorithms should vary behind a common interface', 'When all objects must share one mutable global state', 'When database rows need compression', 'When network packets need routing', 'Strategy encapsulates alternative behaviors so clients can select or replace an algorithm without embedding all variants in the same client.'],
 ['What is high cohesion?', 'A module’s parts contribute to a closely related purpose', 'Every module depends on every other module', 'A file contains many unrelated features', 'All application data is public', 'Cohesion concerns how well a module’s contents belong together. Coupling concerns dependencies between modules.'],
 ['What does the open-closed principle encourage?', 'Extending behavior through appropriate extension points without repeatedly changing stable core code', 'Never modifying any source file after release', 'Making all classes final', 'Opening every internal field to callers', 'The principle encourages stable abstractions with extensible behavior. It does not forbid bug fixes or all changes to existing code.'],
 ['Why put an adapter around an external service SDK?', 'To translate its interface and reduce the spread of vendor-specific details', 'To guarantee the provider never fails', 'To remove the need for network calls', 'To automatically make all calls transactional', 'An adapter gives application code a suitable boundary and localizes changes to the provider’s interface. Reliability still needs explicit handling.'],
 ['Which change most directly reduces tight coupling to a concrete database?', 'Pass a storage interface into the business service', 'Create the database connection inside every business method', 'Expose SQL driver internals to all callers', 'Use a single global mutable connection everywhere', 'Depending on an interface separates business behavior from a particular storage implementation and makes alternative implementations easier to supply.'],
 ['What is a common danger of premature abstraction?', 'Creating complex generality before actual variation is understood', 'Making all future changes impossible by definition', 'Ensuring code duplication never occurs', 'Guaranteeing lower maintenance cost', 'An abstraction based on guessed needs can make simple changes difficult. Concrete repeated needs provide better evidence for useful boundaries.']
 ],
 'Testing': [
 ['What is the typical scope of a unit test?', 'A small unit of behavior exercised in a controlled context', 'An entire production data center', 'Only the visual layout of every page', 'Only manual user acceptance', 'Unit tests target a focused behavior. The precise unit varies, but isolating irrelevant dependencies usually makes failures easier to diagnose.'],
 ['What is an integration test intended to check?', 'Whether components work together across a real boundary', 'Only the syntax of one function', 'Only variable naming conventions', 'Whether a comment is grammatically correct', 'Integration tests exercise interactions such as service-to-database behavior, catching mismatches that isolated unit tests may miss.'],
 ['Which inputs are most useful for boundary-value testing of an accepted range 1 through 100?', '0, 1, 100, and 101', 'Only 50', 'Only random values above 1000', 'Only 25 and 75', 'Values at and just outside the boundaries expose off-by-one and validation errors. Interior values are still useful but do not replace boundary checks.'],
 ['What does a flaky test do?', 'Passes and fails without a relevant change to the behavior under test', 'Always fails on invalid input', 'Runs faster than other tests', 'Checks more than one assertion', 'Flakiness often comes from timing, shared state, uncontrolled randomness, or unreliable external dependencies. It undermines trust in test results.'],
 ['What is property-based testing?', 'Checking general invariants over many generated inputs', 'Testing only object field names', 'Running each test exactly once with a handwritten example', 'Replacing all assertions with logs', 'Instead of listing only examples, a property test generates cases for a rule, such as sorting preserving elements and producing nondecreasing order.'],
 ['Why does 100% line coverage not prove correctness?', 'Executed lines may still have weak assertions or untested combinations', 'Coverage tools never execute code', 'Coverage implies every requirement is satisfied', 'Every bug must live in an unexecuted line', 'Coverage measures execution, not the quality of expected outcomes or completeness of requirements, branches, and input combinations.'],
 ['What is a test double?', 'A substitute for a real collaborator used during testing', 'A test executed twice by definition', 'An assertion with two equal signs', 'A duplicate production database that must be public', 'Stubs, fakes, spies, and mocks are kinds of doubles with different roles. They can control dependencies but may diverge from real behavior.'],
 ['What is a regression test for?', 'Detecting the return of a previously fixed bug or a break in established behavior', 'Guaranteeing that requirements never change', 'Measuring only CPU temperature', 'Replacing all code review', 'A regression test preserves evidence of expected behavior across changes. A bug-specific test is especially useful when it fails before the fix and passes afterward.']
 ],
 'Git': [
 ['What does the Git staging area represent?', 'The content selected for the next commit', 'Only files already pushed to a remote', 'A second remote repository', 'A list of ignored files only', 'The index lets you choose what to commit independently of other working-tree edits. A commit records the staged snapshot.'],
 ['How does git fetch differ from git pull?', 'Fetch retrieves remote updates; pull also integrates them into the current branch', 'Fetch always deletes local commits', 'Pull never contacts a remote', 'Fetch rewrites every local branch', 'Pull performs a fetch followed by integration, commonly merge or rebase depending on configuration. Fetch alone does not update your working branch.'],
 ['What does a merge conflict mean?', 'Git needs a person or tool to resolve incompatible changes', 'The repository has permanently lost all history', 'Both branches have identical content', 'The network password is incorrect', 'Git can combine many edits automatically, but conflicting changes require choosing a valid combined result, staging it, and completing the operation.'],
 ['Why is rebasing a shared branch potentially disruptive?', 'It rewrites commit identities that collaborators may already depend on', 'It always deletes every file', 'It disables future merges permanently', 'It uploads secrets automatically', 'Rebase recreates commits on a different base. Collaborators with the previous history must reconcile the rewritten history, so coordination matters.'],
 ['Which operation normally undoes a committed change by adding a new commit?', 'git revert', 'git reset --hard', 'git clean -fd', 'git fetch', 'Revert records an inverse change while preserving history. Reset instead moves a branch reference and can discard local work depending on mode.'],
 ['What does .gitignore do for a file that is already tracked?', 'It does not stop Git tracking that file', 'It erases the file from all previous commits', 'It automatically encrypts the file', 'It immediately removes the file from the remote', 'Ignore rules primarily affect untracked files. Stopping tracking requires an explicit index change; removing sensitive data from history is a separate task.'],
 ['What is a detached HEAD state?', 'HEAD points directly to a commit rather than to a branch', 'The repository has no commits', 'The remote server is offline', 'Every branch has been deleted', 'You can inspect or make commits in detached HEAD. Creating a branch is a way to retain new work under a convenient reference.'],
 ['What is git cherry-pick commonly used for?', 'Applying the change from a selected commit onto the current branch', 'Downloading every remote branch', 'Combining all repository files into one file', 'Deleting every merge commit', 'Cherry-pick replays a selected commit’s change, usually creating a new commit identity. It can require conflict resolution.']
 ],
 'Security basics': [
 ['What is the primary defense against SQL injection in query values?', 'Parameterized queries with bound values', 'Concatenating values after trimming whitespace', 'Hiding the database hostname', 'Using only short passwords', 'Parameters separate query structure from data. Dynamic identifiers still need suitable allowlisting; escaping alone is more error-prone.'],
 ['How should passwords normally be stored for later verification?', 'With a salted, deliberately expensive password-hashing scheme', 'As reversible plaintext with a hidden filename', 'As unsalted fast general-purpose hashes', 'In browser-visible JavaScript', 'Password hashing slows offline guessing; unique salts prevent identical passwords from sharing identical stored hashes and defeat reusable precomputed tables.'],
 ['What is the difference between authentication and authorization?', 'Authentication verifies identity; authorization checks permitted actions', 'They both mean encrypting network traffic', 'Authorization always happens before any identity is known', 'Authentication grants every verified user all permissions', 'A valid identity does not imply access to every resource. Authorization must enforce the permissions relevant to each operation.'],
 ['What does the principle of least privilege require?', 'Grant only the access needed for the task', 'Make every service an administrator', 'Share one credential across all systems', 'Allow all actions until an incident happens', 'Limiting permissions reduces the scope of mistakes and compromises. Roles and service accounts should receive only necessary access.'],
 ['Which control directly helps prevent reflected or stored XSS when rendering untrusted text?', 'Context-appropriate output encoding and safe rendering APIs', 'Disabling database indexes', 'Increasing HTTP timeouts', 'Using sequential user IDs', 'Encoding prevents text from being interpreted as executable markup or script in its output context. Rich HTML needs sanitization; CSP is an additional layer.'],
 ['What is CSRF?', 'Tricking a browser into making an unwanted authenticated request using ambient credentials', 'Guessing a file checksum', 'Reading a disk after power loss', 'An algorithm for sorting certificates', 'Automatically sent cookies can accompany attacker-triggered requests. CSRF tokens, appropriate SameSite cookies, and origin checks can help, depending on the application.'],
 ['What does HTTPS with correctly validated TLS normally provide?', 'Transport confidentiality, integrity, and server authentication', 'Proof that the application has no security bugs', 'Automatic authorization for all API actions', 'Protection for data after a compromised endpoint decrypts it', 'TLS protects data in transit and authenticates the server under its trust model. It does not secure compromised endpoints or fix application logic.'],
 ['Where should production secrets generally be managed?', 'In a controlled secret-management system with restricted access', 'In a public repository', 'Inside downloadable frontend code', 'In issue titles so they are easy to search', 'Secrets need controlled access, rotation, and appropriate auditing. Client-side code and repository history are unsuitable places to hide confidential credentials.']
 ],
 'Concurrency': [
 ['What is a race condition?', 'Correctness depends on an uncontrolled ordering of concurrent events', 'Any program that uses two functions', 'An algorithm that finishes early', 'A compiler optimization that always preserves output', 'A race occurs when timing or interleaving can alter required behavior. Shared state is a common source, but races can also involve files or distributed operations.'],
 ['Why can counter++ lose updates when used concurrently without synchronization?', 'The read, increment, and write can interleave', 'Integers cannot be shared between threads', 'Increment always changes the counter by two', 'Every CPU instruction is a transaction across all memory', 'Two workers can read the same value and both write the same incremented value. An atomic read-modify-write or suitable lock prevents this pattern.'],
 ['What does a mutex provide?', 'Mutual exclusion for a protected critical section', 'A guarantee that every program is deadlock-free', 'Unlimited parallel writes to protected state', 'Automatic persistence after power failure', 'A mutex lets one holder enter the critical section at a time. Correct lock scope and consistent use are still required.'],
 ['Which situation can cause deadlock?', 'Two threads each hold a lock the other needs, with neither able to proceed', 'A task finishes before its deadline', 'A queue becomes temporarily empty', 'Two independent read-only computations run together', 'A cycle of waiting can deadlock when locks are held and cannot be forcibly taken. Consistent lock ordering is a common prevention technique.'],
 ['What is the distinction between concurrency and parallelism?', 'Concurrency handles overlapping tasks; parallelism executes work simultaneously', 'They always mean exactly one task at a time', 'Concurrency requires multiple CPU cores', 'Parallelism cannot occur with threads', 'A single core can interleave concurrent tasks. Multiple execution resources can run tasks at the same moment.'],
 ['Why should a condition-variable wait usually recheck its predicate in a loop?', 'Wakeups do not guarantee the required condition still holds', 'A loop makes every wait nonblocking', 'The predicate must always be false', 'Condition variables permanently retain every notification', 'Spurious wakeups or another thread consuming the resource can invalidate the condition. Recheck while holding the associated lock.'],
 ['What does a counting semaphore commonly control?', 'How many workers may access a bounded resource concurrently', 'The exact execution order of all CPU instructions', 'Which branch a compiler chooses', 'Whether a network address is valid', 'A semaphore maintains permits. Acquiring consumes a permit and releasing returns one, enabling bounded concurrent access.'],
 ['What is backpressure in a producer-consumer system?', 'Slowing or limiting producers when consumers cannot keep up', 'Adding an infinite buffer to hide all overload', 'Retrying every failed request immediately forever', 'Removing all queue size limits', 'Backpressure propagates capacity limits upstream to prevent unbounded accumulation. Bounded queues, demand signals, and admission control are common mechanisms.']
 ],
 'System design': [
 ['What is horizontal scaling?', 'Adding more instances to share workload', 'Adding RAM to one machine only', 'Compressing every database row', 'Increasing a single request’s timeout', 'Horizontal scaling adds nodes; vertical scaling increases one node’s resources. Distribution introduces coordination and data-placement concerns.'],
 ['What is a load balancer’s main role?', 'Distributing incoming requests among service instances', 'Guaranteeing that every database write is serializable', 'Replacing all application servers', 'Ensuring every response is cached forever', 'A load balancer spreads traffic and may avoid unhealthy instances. Session state, retries, and health-check behavior still require design choices.'],
 ['What happens on a cache miss in the cache-aside pattern?', 'The application reads the backing store and typically populates the cache', 'The backing store is always deleted', 'The application must return a permanent error', 'Every cached item is synchronously invalidated', 'Cache-aside puts the application in charge of loading missed data. Invalidation and stale reads remain important design concerns.'],
 ['During a network partition, what tension does the CAP theorem describe?', 'A system cannot guarantee both linearizable consistency and availability for every request', 'A system can never use caching and replication together', 'A system must always choose any two properties even without partitions', 'Latency and disk capacity must be identical', 'CAP availability requires a response from non-failing nodes, and consistency is single-copy/linearizable behavior. During partitions, some requests must sacrifice one guarantee.'],
 ['How does replication differ from sharding?', 'Replication copies data; sharding partitions data across nodes', 'Replication partitions data and sharding always copies all data', 'Both mean deleting old rows', 'Neither can be used with the other', 'Replicas improve availability and can serve reads; shards distribute data and workload. A system can replicate each shard.'],
 ['Why should consumers tolerate duplicate messages with at-least-once delivery?', 'A message may be redelivered after a failure or uncertain acknowledgment', 'The queue guarantees duplicates never occur', 'Every message is intentionally discarded once', 'Only one consumer may ever exist', 'At-least-once delivery favors eventual delivery over uniqueness. Deduplication and idempotent effects help make redelivery safe.'],
 ['What is the purpose of a circuit breaker around a failing dependency?', 'Temporarily stop calls to reduce cascading failures and allow recovery', 'Retry all requests continuously without delay', 'Guarantee the dependency can never fail again', 'Replace all monitoring', 'A circuit breaker opens after a failure threshold, then probes recovery according to policy. It complements timeouts and bounded retries.'],
 ['What does a p99 latency of 800 ms mean?', 'About 99% of measured request latencies are at or below 800 ms', 'Every request takes exactly 800 ms', 'The average latency is necessarily 800 ms', 'Only 1% of requests finished successfully', 'Percentiles describe the latency distribution. Tail latency can reveal poor experiences that an average hides; it is not a success-rate measure.']
 ],
 'Cloud / DevOps': [
 ['What is a key difference between a typical container and a virtual machine?', 'Containers share a host kernel; VMs run guest operating systems on virtualized hardware', 'Containers always include a separate guest kernel', 'VMs cannot isolate processes', 'Containers require no security configuration', 'Containers isolate processes using OS facilities, while VMs virtualize hardware. Sharing a kernel affects compatibility and isolation boundaries.'],
 ['What is continuous integration primarily about?', 'Frequently integrating changes and automatically checking them', 'Manually deploying once a year', 'Giving production access to every visitor', 'Avoiding version control', 'CI combines changes regularly with automated checks to detect integration problems early. Deployment is a separate step in the delivery process.'],
 ['How does continuous delivery differ from continuous deployment?', 'Delivery keeps changes releasable; deployment automatically releases passing changes to production', 'Delivery means no testing; deployment means only testing', 'Both require manual compilation on a developer’s laptop', 'Deployment forbids automated releases', 'Continuous delivery can retain a manual release decision. Continuous deployment takes qualifying changes through to production automatically.'],
 ['What is infrastructure as code?', 'Managing infrastructure through versioned machine-readable definitions', 'Documenting servers only with screenshots', 'Editing production machines manually without records', 'Putting all application data in source files', 'Infrastructure definitions support review, repeatability, and change tracking. Secrets and environment-specific values still need appropriate handling.'],
 ['What is a blue-green deployment?', 'Maintaining two environments and switching traffic to the prepared new version', 'Deploying all changes directly to one live process with no fallback', 'Running tests only on green-colored terminals', 'Randomly terminating half the database nodes', 'Traffic moves from the current environment to a prepared one. Rollback can be easier, but shared data and schema compatibility still matter.'],
 ['What is a canary release?', 'Exposing a new version to a small portion of traffic before expanding it', 'Releasing to every user simultaneously without measurement', 'Keeping a release permanently disconnected from real traffic', 'Deleting all old versions before testing', 'A canary limits exposure while metrics and errors are observed. Progression or rollback should follow meaningful health signals.'],
 ['How do readiness and liveness probes differ?', 'Readiness asks whether an instance should receive traffic; liveness asks whether it should be restarted', 'They always trigger the same action', 'Readiness verifies only repository permissions', 'Liveness measures only monthly cloud cost', 'An unready instance can remain running while excluded from traffic. A failing liveness probe can trigger restart, so overly aggressive checks can make incidents worse.'],
 ['Which set best represents the common observability signals?', 'Metrics, logs, and traces', 'Passwords, cookies, and private keys', 'Branches, tags, and merge conflicts', 'Images, fonts, and color palettes', 'Metrics summarize behavior, logs capture events, and traces follow work across boundaries. Correlation makes diagnosing distributed failures easier.']
 ]
};
